version: "3.8"
services:
  db:
    container_name: database_pg
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - dock-db-test
  app:
    restart: always
    build: ./
    image: app:latest
    volumes:
      - ../backend:/backend
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - dock-db-test
    links:
      - db
  frontend:
    restart: always
    build: ../frontend
    image: frontend:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - app
    networks:
      - dock-db-test
    links:
      - app
networks:
  dock-db-test:
    external: false
    name: dock-db-test
