version: "3.8"
services:
  db:
    container_name: database_pg
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_NAME=test123
      - POSTGRES_USER=test123
      - POSTGRES_PASSWORD=asd123
    ports:
      - 5432:5432
    volumes:
      - ./db/db_sql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dock-db-test
  app :
    restart: always
    build: ./
    image: app:latest
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - dock-db-test
networks:
  dock-db-test:
    external: false
    name: dock-db-test